name: CI
on: 
  pull_request:
    branches: [develop, master]
  push:
    branches: [develop, master]  

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
        SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
        SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}

    steps: 
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with: 
          node-version: "12.x"
      - run: npm CI
      - run: npm run format:check
      - run: npm test -- --coverage
        env:
          CI: true